name: Update README

on:
  schedule:
    - cron: '45 9 * * 1-5' # S'exécute à 06:30 UTC les jours de semaine

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
        
      - name: Install Dependencies
        run: npm install

      - name: Update README
        run: node index.js

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v4.x
        with:
          author_name: LucasB19
          author_email: ld.berry@outlook.com
          message: "Automatically update README"
          add: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

