name: Update README

on:
  schedule:
    - cron: '30 6 * * 1-5' # S'exécute à 06:30 les jours de semaine

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install Dependencies
      run: npm install
    - name: Update README
      run: node index.js
    - name: Setup Git Identity
      run: |
        git config --global user.email "ld.berry@outlook.com"
        git config --global user.name "LucasB19"
    - name: Commit and Push if needed
      run: |
        git add README.md
        git commit -m "Update README" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
