name: Update README

on:
  schedule:
    - cron: '30 6 * * 1-5' # S'exécute tous les jours à minuit

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install Dependencies
      run: npm install
    - name: Update README
      run: node index.js
    - name: Commit and Push if needed
      run: |
        git config --global user.email "ld.berry@outlook.com
        git config --global user.name "LucasB19"
        git commit -am "Update README" || echo "No changes to commit"
        git push
